[env:m5stack_paper]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38/platform-espressif32.zip
board = m5stack_paper
framework = arduino
lib_deps = 
    m5stack/M5Unified
    bblanchon/ArduinoJson@^7
monitor_speed = 115200
build_flags = 
    -DBOARD_HAS_PSRAM