[env:m5stack_paper]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38/platform-espressif32.zip
board = m5stack_paper
framework = arduino
extra_scripts = pre:scripts/pio_set_ota_repo.py
lib_deps = 
    m5stack/M5Unified
    bblanchon/ArduinoJson@^7
monitor_speed = 115200
build_flags = 
    -DBOARD_HAS_PSRAM
    ; Server log submission (enabled by default)
    -DENABLE_SERVER_LOGS
    ; Uncomment to enable debug logs (define DEBUG_LOGS)
    ; -DDEBUG_LOGS
    ; Uncomment to force OTA check/attempt once on next cold boot (testing only)
    ; -DFORCE_OTA_ON_NEXT_BOOT